cd /storage/home/users/pjt6/chicken_data
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELLEFT_1*.bam DARKTELLEFT_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_24H_2*.bam LIGHTRETLEFT_24H_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_6H_2*.bam LIGHTTELLEFT_6H_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELLEFT_5*.bam DARKTELLEFT_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_24H_3*.bam LIGHTRETLEFT_24H_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELRIGHT_1*.bam DARKTELRIGHT_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_24H_2*.bam LIGHTRETRIGHT_24H_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_6H_2*.bam LIGHTTELRIGHT_6H_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELRIGHT_5*.bam DARKTELRIGHT_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_24H_3*.bam LIGHTRETRIGHT_24H_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_6H_1*.bam LIGHTTELLEFT_6H_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_24H_3*.bam LIGHTTELLEFT_24H_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_6H_2*.bam LIGHTRETLEFT_6H_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETLEFT_5*.bam DARKRETLEFT_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_24H_4*.bam LIGHTTELLEFT_24H_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_6H_1*.bam LIGHTTELRIGHT_6H_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_24H_3*.bam LIGHTTELRIGHT_24H_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_6H_2*.bam LIGHTRETRIGHT_6H_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETRIGHT_5*.bam DARKRETRIGHT_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_24H_4*.bam LIGHTTELRIGHT_24H_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_6H_1*.bam LIGHTRETLEFT_6H_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELLEFT_2*.bam DARKTELLEFT_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_6H_3*.bam LIGHTTELLEFT_6H_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_6H_4*.bam LIGHTTELLEFT_6H_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_24H_4*.bam LIGHTRETLEFT_24H_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_6H_1*.bam LIGHTRETRIGHT_6H_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELRIGHT_2*.bam DARKTELRIGHT_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_6H_3*.bam LIGHTTELRIGHT_6H_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_6H_4*.bam LIGHTTELRIGHT_6H_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_24H_4*.bam LIGHTRETRIGHT_24H_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_24H_1*.bam LIGHTTELLEFT_24H_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETLEFT_1*.bam DARKRETLEFT_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETLEFT_3*.bam DARKRETLEFT_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_6H_3*.bam LIGHTRETLEFT_6H_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_24H_5*.bam LIGHTTELLEFT_24H_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_24H_1*.bam LIGHTTELRIGHT_24H_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETRIGHT_1*.bam DARKRETRIGHT_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETRIGHT_3*.bam DARKRETRIGHT_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_6H_3*.bam LIGHTRETRIGHT_6H_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_24H_5*.bam LIGHTTELRIGHT_24H_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_24H_1*.bam LIGHTRETLEFT_24H_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELLEFT_3*.bam DARKTELLEFT_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELLEFT_4*.bam DARKTELLEFT_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_6H_5*.bam LIGHTTELLEFT_6H_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_24H_5*.bam LIGHTRETLEFT_24H_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_24H_1*.bam LIGHTRETRIGHT_24H_1.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELRIGHT_3*.bam DARKTELRIGHT_3.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKTELRIGHT_4*.bam DARKTELRIGHT_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_6H_5*.bam LIGHTTELRIGHT_6H_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_6H_5*.bam LIGHTRETLEFT_6H_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELLEFT_24H_2*.bam LIGHTTELLEFT_24H_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETLEFT_2*.bam DARKRETLEFT_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETLEFT_4*.bam DARKRETLEFT_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETLEFT_6H_4*.bam LIGHTRETLEFT_6H_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_6H_5*.bam LIGHTRETRIGHT_6H_5.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTTELRIGHT_24H_2*.bam LIGHTTELRIGHT_24H_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETRIGHT_2*.bam DARKRETRIGHT_2.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf DARKRETRIGHT_4*.bam DARKRETRIGHT_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_6H_4*.bam LIGHTRETRIGHT_6H_4.exons.counts
python ./dexseq_count.py -p yes -f bam -r pos Gallus_gallus.GRCg6a.99.exons.gtf LIGHTRETRIGHT_24H_5*.bam LIGHTRETRIGHT_24H_5.exons.counts
