from collections import defaultdict

import os


samp = """DARKRETLEFT	DARKRETLEFT_1
DARKRETLEFT	DARKRETLEFT_2
DARKRETLEFT	DARKRETLEFT_3
DARKRETLEFT	DARKRETLEFT_4
DARKRETLEFT	DARKRETLEFT_5
DARKRETRIGHT	DARKRETRIGHT_1
DARKRETRIGHT	DARKRETRIGHT_2
DARKRETRIGHT	DARKRETRIGHT_3
DARKRETRIGHT	DARKRETRIGHT_4
DARKRETRIGHT	DARKRETRIGHT_5
DARKTELLEFT	DARKTELLEFT_1
DARKTELLEFT	DARKTELLEFT_2
DARKTELLEFT	DARKTELLEFT_3
DARKTELLEFT	DARKTELLEFT_4
DARKTELLEFT	DARKTELLEFT_5
DARKTELRIGHT	DARKTELRIGHT_1
DARKTELRIGHT	DARKTELRIGHT_2
DARKTELRIGHT	DARKTELRIGHT_3
DARKTELRIGHT	DARKTELRIGHT_4
DARKTELRIGHT	DARKTELRIGHT_5
LIGHTRETLEFT_24H	LIGHTRETLEFT_24H_1
LIGHTRETLEFT_24H	LIGHTRETLEFT_24H_2
LIGHTRETLEFT_24H	LIGHTRETLEFT_24H_3
LIGHTRETLEFT_24H	LIGHTRETLEFT_24H_4
LIGHTRETLEFT_24H	LIGHTRETLEFT_24H_5
LIGHTRETLEFT_6H	LIGHTRETLEFT_6H_1
LIGHTRETLEFT_6H	LIGHTRETLEFT_6H_2
LIGHTRETLEFT_6H	LIGHTRETLEFT_6H_3
LIGHTRETLEFT_6H	LIGHTRETLEFT_6H_4
LIGHTRETLEFT_6H	LIGHTRETLEFT_6H_5
LIGHTRETRIGHT_24H	LIGHTRETRIGHT_24H_1
LIGHTRETRIGHT_24H	LIGHTRETRIGHT_24H_2
LIGHTRETRIGHT_24H	LIGHTRETRIGHT_24H_3
LIGHTRETRIGHT_24H	LIGHTRETRIGHT_24H_4
LIGHTRETRIGHT_24H	LIGHTRETRIGHT_24H_5
LIGHTRETRIGHT_6H	LIGHTRETRIGHT_6H_1
LIGHTRETRIGHT_6H	LIGHTRETRIGHT_6H_2
LIGHTRETRIGHT_6H	LIGHTRETRIGHT_6H_3
LIGHTRETRIGHT_6H	LIGHTRETRIGHT_6H_4
LIGHTRETRIGHT_6H	LIGHTRETRIGHT_6H_5
LIGHTTELLEFT_24H	LIGHTTELLEFT_24H_1
LIGHTTELLEFT_24H	LIGHTTELLEFT_24H_2
LIGHTTELLEFT_24H	LIGHTTELLEFT_24H_3
LIGHTTELLEFT_24H	LIGHTTELLEFT_24H_4
LIGHTTELLEFT_24H	LIGHTTELLEFT_24H_5
LIGHTTELLEFT_6H	LIGHTTELLEFT_6H_1
LIGHTTELLEFT_6H	LIGHTTELLEFT_6H_2
LIGHTTELLEFT_6H	LIGHTTELLEFT_6H_3
LIGHTTELLEFT_6H	LIGHTTELLEFT_6H_4
LIGHTTELLEFT_6H	LIGHTTELLEFT_6H_5
LIGHTTELRIGHT_24H	LIGHTTELRIGHT_24H_1
LIGHTTELRIGHT_24H	LIGHTTELRIGHT_24H_2
LIGHTTELRIGHT_24H	LIGHTTELRIGHT_24H_3
LIGHTTELRIGHT_24H	LIGHTTELRIGHT_24H_4
LIGHTTELRIGHT_24H	LIGHTTELRIGHT_24H_5
LIGHTTELRIGHT_6H	LIGHTTELRIGHT_6H_1
LIGHTTELRIGHT_6H	LIGHTTELRIGHT_6H_2
LIGHTTELRIGHT_6H	LIGHTTELRIGHT_6H_3
LIGHTTELRIGHT_6H	LIGHTTELRIGHT_6H_4
LIGHTTELRIGHT_6H	LIGHTTELRIGHT_6H_5""".split("\n")
rowname = ''
condition = ''
libtype = ''

for i in samp:
    cond, sampl = i.split("\t")
    rowname = rowname + sampl + ", "
    condition = condition + cond + ", "
    libtype = libtype + "paired-end" + ", "

print("""sampleTable = data.frame(
   row.names = c(%s\n\n""" % rowname)

print("""condition = c(%s\n\n""" % condition)

print("""libType = c((%s\n\n""" % libtype)



###

sampleTable = data.frame(
   row.names = c("DARKRETLEFT_1", "DARKRETLEFT_2", "DARKRETLEFT_3", "DARKRETLEFT_4", "DARKRETLEFT_5", 
   "DARKRETRIGHT_1", "DARKRETRIGHT_2", "DARKRETRIGHT_3", "DARKRETRIGHT_4", "DARKRETRIGHT_5", "DARKTELLEFT_1", 
   "DARKTELLEFT_2", "DARKTELLEFT_3", "DARKTELLEFT_4", "DARKTELLEFT_5", "DARKTELRIGHT_1", "DARKTELRIGHT_2",
   "DARKTELRIGHT_3", "DARKTELRIGHT_4", "DARKTELRIGHT_5", "LIGHTRETLEFT_24H_1", "LIGHTRETLEFT_24H_2", "LIGHTRETLEFT_24H_3", 
   "LIGHTRETLEFT_24H_4", "LIGHTRETLEFT_24H_5", "LIGHTRETLEFT_6H_1", "LIGHTRETLEFT_6H_2", "LIGHTRETLEFT_6H_3", "LIGHTRETLEFT_6H_4", 
   "LIGHTRETLEFT_6H_5", "LIGHTRETRIGHT_24H_1", "LIGHTRETRIGHT_24H_2", "LIGHTRETRIGHT_24H_3", "LIGHTRETRIGHT_24H_4", "LIGHTRETRIGHT_24H_5", 
   "LIGHTRETRIGHT_6H_1", "LIGHTRETRIGHT_6H_2", "LIGHTRETRIGHT_6H_3", "LIGHTRETRIGHT_6H_4", "LIGHTRETRIGHT_6H_5", 
   "LIGHTTELLEFT_24H_1", "LIGHTTELLEFT_24H_2", "LIGHTTELLEFT_24H_3", "LIGHTTELLEFT_24H_4", "LIGHTTELLEFT_24H_5", "LIGHTTELLEFT_6H_1", 
   "LIGHTTELLEFT_6H_2", "LIGHTTELLEFT_6H_3", "LIGHTTELLEFT_6H_4", "LIGHTTELLEFT_6H_5", "LIGHTTELRIGHT_24H_1", "LIGHTTELRIGHT_24H_2",
   "LIGHTTELRIGHT_24H_3", "LIGHTTELRIGHT_24H_4", "LIGHTTELRIGHT_24H_5", "LIGHTTELRIGHT_6H_1", "LIGHTTELRIGHT_6H_2", "LIGHTTELRIGHT_6H_3", 
   "LIGHTTELRIGHT_6H_4", "LIGHTTELRIGHT_6H_5"),
   condition = c("DARKRETLEFT",  "DARKRETLEFT",  "DARKRETLEFT",  "DARKRETLEFT",  "DARKRETLEFT",  "DARKRETRIGHT",  "DARKRETRIGHT",  
   "DARKRETRIGHT",  "DARKRETRIGHT",  "DARKRETRIGHT",  "DARKTELLEFT",  "DARKTELLEFT",  "DARKTELLEFT",  "DARKTELLEFT",  "DARKTELLEFT",  
   "DARKTELRIGHT",  "DARKTELRIGHT",  "DARKTELRIGHT",  "DARKTELRIGHT",  "DARKTELRIGHT",  "LIGHTRETLEFT_24H",  "LIGHTRETLEFT_24H",  
   "LIGHTRETLEFT_24H",  "LIGHTRETLEFT_24H",  "LIGHTRETLEFT_24H",  "LIGHTRETLEFT_6H",  "LIGHTRETLEFT_6H",  "LIGHTRETLEFT_6H",  "LIGHTRETLEFT_6H",  
   "LIGHTRETLEFT_6H",  "LIGHTRETRIGHT_24H",  "LIGHTRETRIGHT_24H",  "LIGHTRETRIGHT_24H",  "LIGHTRETRIGHT_24H",  "LIGHTRETRIGHT_24H", 
   "LIGHTRETRIGHT_6H",  "LIGHTRETRIGHT_6H",  "LIGHTRETRIGHT_6H",  "LIGHTRETRIGHT_6H",  "LIGHTRETRIGHT_6H",  "LIGHTTELLEFT_24H", 
   "LIGHTTELLEFT_24H",  "LIGHTTELLEFT_24H",  "LIGHTTELLEFT_24H",  "LIGHTTELLEFT_24H",  "LIGHTTELLEFT_6H",  "LIGHTTELLEFT_6H",  
   "LIGHTTELLEFT_6H",  "LIGHTTELLEFT_6H",  "LIGHTTELLEFT_6H",  "LIGHTTELRIGHT_24H",  "LIGHTTELRIGHT_24H",  "LIGHTTELRIGHT_24H", 
   "LIGHTTELRIGHT_24H",  "LIGHTTELRIGHT_24H",  "LIGHTTELRIGHT_6H",  "LIGHTTELRIGHT_6H",  "LIGHTTELRIGHT_6H",  "LIGHTTELRIGHT_6H", 
   "LIGHTTELRIGHT_6H"),
   libType = c("paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end",
   "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", 
   "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end",
   "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", 
   "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", 
   "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end", "paired-end"))
